apiVersion: am.argocd/v1
kind: ServiceDeploy
service: am-modern-ui
enabled: true
owners: ui
source:
  repo: am-modern-ui
  path: am_app/argocd.yaml
chart:
  repoURL: https://github.com/AM-Portfolio/am-pipelines.git
  path: helm/universal-chart
  targetRevision: main
helm:
  releaseName: am-modern-ui
  valuesPath: am_app/helm
valuesRepoURL: https://github.com/AM-Portfolio/am-modern-ui.git
valuesTargetRevision: main
envs:
  prod:
    enabled: true
    namespace: am-apps-prod
