# Analysis options for am_analysis_core package

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
