import '../../../internal/domain/entities/trade_controller_entities.dart';
import '../../../internal/domain/enums/derivative_types.dart';
import '../../../internal/domain/enums/exchange_types.dart';
import '../../../internal/domain/enums/fundamental_reasons.dart';
import '../../../internal/domain/enums/market_segments.dart';
import '../../../internal/domain/enums/option_types.dart';
import '../../../internal/domain/enums/psychology_factors.dart';
import '../../../internal/domain/enums/technical_reasons.dart';
import '../../../internal/domain/enums/trade_directions.dart';
import '../../../internal/domain/enums/trade_statuses.dart';

/// Mapper to convert form data to domain entities
class TradeFormMapper {
  const TradeFormMapper._();

  /// Maps form data to TradeDetails entity
  static TradeDetails mapToTradeDetails({
    required String symbol,
    required ExchangeTypes? exchange,
    required MarketSegments? segment,
    required String? isin,
    required String? description,
    required DerivativeTypes? derivativeType,
    required double? strikePrice,
    required OptionTypes? optionType,
    required DateTime? expiryDate,
    required DateTime? entryDate,
    required double entryPrice,
    required double entryQuantity,
    required DateTime? exitDate,
    required double? exitPrice,
    required double? exitQuantity,
    required TradeDirections direction,
    required TradeStatuses status,
    required List<EntryPsychologyFactors> entryPsychology,
    required List<ExitPsychologyFactors> exitPsychology,
    required List<TechnicalReasons> technicalReasons,
    required List<FundamentalReasons> fundamentalReasons,
    required String? strategy,
    required String? notes,
    required String? portfolioId,
    required List<String> attachments,
  }) {
    // Construct InstrumentInfo
    final instrumentInfo = InstrumentInfo(
      symbol: symbol.toUpperCase(),
      exchange: exchange,
      segment: segment,
      isin: isin,
      description: description,
      derivativeInfo: derivativeType != null
          ? DerivativeInfo(
              derivativeType: derivativeType,
              strikePrice: strikePrice,
              optionType: optionType,
              expiryDate: expiryDate,
            )
          : null,
    );

    // Construct EntryExitInfo for entry
    final entryInfo = EntryExitInfo(timestamp: entryDate, price: entryPrice, quantity: entryQuantity.toInt());

    // Construct EntryExitInfo for exit (if not open)
    final exitInfo = status != TradeStatuses.open && exitDate != null
        ? EntryExitInfo(timestamp: exitDate, price: exitPrice, quantity: exitQuantity?.toInt())
        : null;

    // Construct TradePsychologyData
    final psychologyData = TradePsychologyData(
      entryPsychologyFactors: entryPsychology.isNotEmpty ? entryPsychology : null,
      exitPsychologyFactors: exitPsychology.isNotEmpty ? exitPsychology : null,
    );

    // Construct TradeEntryExitReasoning
    final entryReasoning = TradeEntryExitReasoning(
      technicalReasons: technicalReasons.isNotEmpty ? technicalReasons : null,
      fundamentalReasons: fundamentalReasons.isNotEmpty ? fundamentalReasons : null,
      strategy: strategy,
    );

    // Construct the complete TradeDetails entity
    return TradeDetails(
      tradeId: '', // Will be generated by server
      portfolioId: portfolioId ?? '',
      instrumentInfo: instrumentInfo,
      tradePositionType: direction,
      status: status,
      entryInfo: entryInfo,
      exitInfo: exitInfo,
      psychologyData: psychologyData,
      entryReasoning: entryReasoning,
      notes: notes,
      strategy: strategy,
      attachments: attachments.isNotEmpty ? attachments.map((url) => Attachment(fileUrl: url)).toList() : null,
    );
  }
}
