apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "universal-chart.fullname" . }}-config
data:
  config.json: |
    {
      "domain": {{ .Values.appConfig.domain | quote }},
      "env": {{ .Values.environment | default "dev" | quote }},
      "google": {
        "webClientId": {{ .Values.appConfig.googleWebClientId | default "" | quote }}
      }
    }
