# Prod Environment — am-modern-ui
# Prod app host (prep). Do not remove munish from infra Traefik.
environment: prod

appConfig:
  domain: "am.asrax.in"
  googleWebClientId: "307768822337-ad7tee4d82cc0b4flgrfs157e5e6rc0g.apps.googleusercontent.com"

replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: am.asrax.in
      paths:
        - path: /
          pathType: Prefix
