environment: preprod

global:
  image:
    imagePullSecrets:
      - name: github-registry-secret

config:
  env: "preprod"

security:
  hosts:
    - host: modern-ui.preprod.local
      paths:
        - path: /
          pathType: Prefix

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: modern-ui.preprod.local
      paths:
        - path: /
          pathType: Prefix

vault:
  enabled: false
