# Preprod Environment — am-modern-ui
# Preprod app host only — am.asrax.in reserved for prod
environment: preprod

appConfig:
  domain: "am-preprod.asrax.in"

replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: am-preprod.asrax.in
      paths:
        - path: /
          pathType: Prefix
