global:
  image:
    imagePullSecrets:
      - name: github-registry-secret

replicaCount: 1
service:
  port: 8080
language: flutter
environment: dev

global:
  image:
    registry: ghcr.io/am-portfolio
    pullPolicy: Always
    imagePullSecrets:
      - name: github-registry-secret

appConfig:
  domain: "am.munish.org"

configMap:
  enabled: true
  mountPath: /usr/share/nginx/html/config.json
  subPath: config.json

image:
  repository: am-modern-ui
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: github-registry-secret

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  hosts:
    - host: am-dev.asrax.in
      paths:
        - path: /
          pathType: Prefix

probes:
  port: 8080
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  env: "dev"

vault:
  enabled: false
